name: GriefPreventionPlus
main: net.kaikk.mc.gpp.GriefPreventionPlus
version: 13.8
author: [KaiNoMood, EverNife]
softdepend: [Vault, Multiverse-Core, My Worlds, MystCraft, Transporter, TheUnderground, WorldGuard, WorldEdit]
loadbefore: [TheUnderground, GriefPrevention]
commands:
   claim:
      description: Claim with a specified range around your position.
      usage: /Claim [range]
      permission: griefprevention.claims
   adminclaim:
      description: Claim with a specified range around your position.
      usage: /AdminClaim [range]
      permission: griefprevention.adminclaims
   abandonclaim:
      description: Deletes a claim.
      usage: /AbandonClaim
      aliases: [unclaim, declaim, removeclaim, disclaim]
      permission: griefprevention.claims
   abandontoplevelclaim:
      description: Deletes a claim and all its subdivisions.
      usage: /AbandonTopLevelClaim
      permission: griefprevention.claims
   abandonallclaims:
      description: Deletes ALL your claims.
      usage: /AbandonAllClaims
      permission: griefprevention.claims
   trust:
      description: Grants a player full access to your claim(s).
      usage: /Trust <player>  Graants a player permission to build.  See also /UnTrust, /ContainerTrust, /AccessTrust, and /PermissionTrust.
      aliases: tr
      permission: griefprevention.claims
   untrust:
      description: Revokes a player's access to your claim(s).
      usage: /UnTrust <player>
      aliases: ut
      permission: griefprevention.claims
   containertrust:
      description: Grants a player access to your containers.
      usage: /ContainerTrust <player>.  Grants a player access to your inventory, bed, and buttons/levers.
      aliases: ct
      permission: griefprevention.claims
   accesstrust:
      description: Grants a player access to levers and doors in your claim(s) and use of your bed.
      usage: /AccessTrust <player>.  Grants a player access to your bed, buttons, and levers.
      aliases: at
      permission: griefprevention.claims
   entrytrust:
      description: Grants a player entry to your claim(s).
      usage: /EntryTrust <player>.  Grants a player access your claim.
      aliases: et
      permission: griefprevention.claims
   permissiontrust:
      description: Grants a player permission to grant his level of permission to others.
      usage: /PermissionTrust <player>.  Permits a player to share his permission level with others.
      aliases: pt
      permission: griefprevention.claims
   subdivideclaims:
      description: Switches the shovel tool to subdivision mode, used to subdivide your claims.
      usage: /SubdivideClaims
      aliases: [sdc, subdivideclaim]
      permission: griefprevention.claims
   adjustbonusclaimblocks:
      description: Adds or subtracts bonus claim blocks for a player.
      usage: /AdjustBonusClaimBlocks <player> <amount>
      permission: griefprevention.adjustclaimblocks
      aliases: acb
   adjustbonusclaimblocksall:
      description: Adds or subtracts bonus claim blocks for all online players.
      usage: /AdjustBonusClaimBlocksAll <player> <amount>
      permission: griefprevention.adjustclaimblocks
      aliases: acball
   setaccruedclaimblocks:
      description: Updates a player's accrued claim block total.
      usage: /SetAccruedClaimBlocks <player> <amount>
      permission: griefprevention.adjustclaimblocks
      aliases: scb
   deleteclaim:
      description: Deletes the claim you're standing in, even if it's not your claim.
      usage: /DeleteClaim
      permission: griefprevention.deleteclaims
      aliases: dc   
   deleteallclaims:
      description: Deletes all of another player's claims.
      usage: /DeleteAllClaims <player>
      permission: griefprevention.deleteclaims
   adminclaims:
      description: Switches the shovel tool to administrative claims mode.
      usage: /AdminClaims
      permission: griefprevention.adminclaims
      aliases: ac
   restorenature:
      description: Switches the shovel tool to restoration mode.
      usage: /RestoreNature 
      permission: griefprevention.restorenature
      aliases: rn
   restorenatureaggressive:
      description: Switches the shovel tool to aggressive restoration mode.
      usage: /RestoreNatureAggressive 
      permission: griefprevention.restorenatureaggressive
      aliases: rna
   restorenaturefill:
      description: Switches the shovel tool to fill mode.
      usage: /RestoreNatureFill <radius> 
      permission: griefprevention.restorenatureaggressive
      aliases: rnf
   basicclaims:
      description: Switches the shovel tool back to basic claims mode.
      usage: /BasicClaims
      aliases: bc
      permission: griefprevention.claims
   buyclaimblocks:
      description: Purchases additional claim blocks with server money.  Doesn't work on servers without a Vault-compatible economy plugin.
      usage: /BuyClaimBlocks <numberOfBlocks>
      aliases: buyclaim   
      permission: griefprevention.buysellclaimblocks
   sellclaimblocks:
      description: Sells your claim blocks for server money.  Doesn't work on servers without a Vault-compatible economy plugin.
      usage: /SellClaimBlocks <numberOfBlocks>
      aliases: sellclaim
      permission: griefprevention.buysellclaimblocks
   trapped:
      description: Ejects you to nearby unclaimed land.  Has a substantial cooldown period.
      usage: /Trapped
   trustlist:
      description: Lists permissions for the claim you're standing in or the specified claim ID.
      usage: /TrustList <ClaimID>
      permission: griefprevention.claims
   ignoreclaims:
      description: Toggles ignore claims mode.
      usage: /IgnoreClaims
      permission: griefprevention.ignoreclaims
      aliases: ic
   deletealladminclaims:
      description: Deletes all administrative claims.
      usage: /DeleteAllAdminClaims
      permission: griefprevention.adminclaims
   transferclaim:
      description: Converts an administrative claim to a private claim.
      usage: /TransferClaim <player>
      aliases: giveclaim
      permission: griefprevention.transferclaim
   claimslist:
      description: Lists information about a player's claim blocks and claims.
      usage: /ClaimsList or /ClaimsList <player>
      aliases: [claimlist, listclaims]
   claimexplosions:
      description: Toggles whether explosives may be used in a specific land claim.
      usage: /ClaimExplosions
   gpreload:
      description: Reloads Grief Prevention's configuration settings.  Does NOT totally reload the entire plugin.
      usage: /gpreload
      permission: griefprevention.reload
   givepet:
      description: Allows a player to give away a pet he or she tamed.
      usage: /GivePet <player>
      permission: griefprevention.givepet
   gpblockinfo:
      description: Allows an administrator to get technical information about blocks in the world and items in hand.
      usage: /GPBlockInfo
      permission: griefprevention.gpblockinfo
   clearorphanclaims:
      description: Clear orphan claims from the database
      usage: /ClearOrphanClaims
      permission: griefprevention.clearorphanclaims
   claimarea:
      description: Claims an area at specified world, coordinate and range
      usage: /ClaimArea [worldname] [x] [z] [range]
      aliases: [carea]
      permission: griefprevention.claimarea
   tpclaim:
      description: Teleports to a claim corner
      usage: /tpclaim [id]
      permission: griefprevention.tpclaim
   autotrust:
      description: Auto trusts all players and fake players that places or breaks a block in 10 seconds in the claim you are standing on
      usage: /autotrust (while standing in your claim)
      permission: griefprevention.claims
   deleteplayerclaims:
      description: Delete all claims owned by the specified player
      usage: /deleteplayerclaims <PlayerName> [WorldName]
      permission: griefprevention.deleteclaims
   deleteclaimsinworld:
      description: Delete all claims on the specified world
      usage: /deleteclaimsinworld [WorldName]
      permission: griefprevention.deleteclaims
   amountofclaims:
      description: Shows the amount of claims, optionally in the specified world
      usage: /AmountOfClaims [WorldName]
   gpp:
     description: Main command
     usage: /gpp <subComand>
     permission: griefprevention.gpp
permissions:
    griefprevention.createclaims:
        description: Grants permission to create claims.
        default: true
    griefprevention.admin.*:
        description: Grants all administrative functionality.
        children:
            griefprevention.restorenature: true
            griefprevention.restorenatureaggressive: true
            griefprevention.ignoreclaims: true
            griefprevention.adminclaims: true
            griefprevention.adjustclaimblocks: true
            griefprevention.deleteclaims: true
            griefprevention.lava: true
            griefprevention.deathblow: true
            griefprevention.reload: true
            griefprevention.visualizenearbyclaims: true
            griefprevention.overrideclaimcountlimit: true
            griefprevention.transferclaim: true
            griefprevention.claimslistother: true
            griefprevention.clearorphanclaims: true
            griefprevention.claimarea: true
            griefprevention.bypassentryprotection: true
            griefprevention.tpclaim: true
    griefprevention.tpclaim:
        description: Grants permission to use /tpclaim
        default: op
    griefprevention.claimarea:
        description: Grants permission to use /ClaimArea
        default: op
    griefprevention.bypassentryprotection:
        description: Bypass all claims entry protection
        default: op
    griefprevention.clearorphanclaims:
        description: Clear orphan claims from the database
        default: op
    griefprevention.givepet:
        description: Grants permission to use /GivePet.
        default: true
    griefprevention.claimslistother:
        description: Grants permission to use /ClaimsList to get another player's information.
        default: op
    griefprevention.restorenature:
        description: Grants permission to use /RestoreNature.
        default: op
    griefprevention.transferclaim:
        description: Grants permission to use /TransferClaim.
        default: op
    griefprevention.ignoreclaims:
        description: Grants permission to use /IgnoreClaims.
        default: op
    griefprevention.adminclaims:
        description: Grants permission to create administrative claims.
        default: op
    griefprevention.deleteclaims:
        description: Grants permission to delete other players' claims.
        default: op
    griefprevention.adjustclaimblocks:
        description: Grants permission to add or remove bonus blocks from a player's account.
        default: op
    griefprevention.lava:
        description: Grants permission to place lava near the surface and outside of claims.
        default: op
    griefprevention.restorenatureaggressive:
        description: Grants access to /RestoreNatureAggressive and /RestoreNatureFill.
        default: op
    griefprevention.deathblow:
        description: Grants access to /DeathBlow.
        default: op
    griefprevention.reload:
        description: Grants access to /gpreload.
        default: op
    griefprevention.claims:
        description: Grants access to claim-related slash commands.
        default: true
    griefprevention.buysellclaimblocks:
        description: Grants access to claim block buy/sell commands.
        default: true
    griefprevention.visualizenearbyclaims:
        description: Allows a player to see all nearby claims at once.
        default: true
    griefprevention.gpblockinfo:
        description: Grants access to /GPBlockInfo.
        default: op
    griefprevention.overrideclaimcountlimit:
        description: Allows players to create more claims than the limit specified by the config.
        default: op
    griefprevention.claiminfo:
        description: Allows players to check claims size and last seen of the claim owner.
        default: false
    griefprevention.skipclaimexpiration:
        description: Claims owned by a player with this permission will not expire
        default: false
    griefprevention.tpclaim.others:
        description: Allows tping other players to a claim corner
        default: op
